# Generated by Django 4.1.1 on 2022-10-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbase",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
