# Generated by Django 4.1.1 on 2022-12-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(decimal_places=2, default="0", max_digits=10),
            preserve_default=False,
        ),
    ]
