# Generated by Django 4.1.1 on 2022-10-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="full_name", new_name="first_name",
        ),
        migrations.RenameField(model_name="order", old_name="city", new_name="state",),
        migrations.RemoveField(model_name="order", name="address2",),
        migrations.RemoveField(model_name="order", name="post_code",),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
